/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.fala.pulltorefresh.library;

public final class R {
    public static final class anim {
        public static final int slide_in_from_bottom = 0x7f010000;
        public static final int slide_in_from_top = 0x7f010001;
        public static final int slide_out_to_bottom = 0x7f010002;
        public static final int slide_out_to_top = 0x7f010003;
    }
    public static final class attr {
        public static final int contentViewId = 0x7f020000;
        public static final int fastScrollEnabled = 0x7f020001;
        public static final int fastScrollHorizontalThumbDrawable = 0x7f020002;
        public static final int fastScrollHorizontalTrackDrawable = 0x7f020003;
        public static final int fastScrollVerticalThumbDrawable = 0x7f020004;
        public static final int fastScrollVerticalTrackDrawable = 0x7f020005;
        public static final int layoutManager = 0x7f020006;
        public static final int mark_color = 0x7f020007;
        public static final int max_unit_count = 0x7f020008;
        public static final int min_unit = 0x7f020009;
        public static final int min_unit_size = 0x7f02000a;
        public static final int per_unit_count = 0x7f02000b;
        public static final int ptrAdapterViewBackground = 0x7f02000c;
        public static final int ptrAnimationStyle = 0x7f02000d;
        public static final int ptrDrawable = 0x7f02000e;
        public static final int ptrDrawableBottom = 0x7f02000f;
        public static final int ptrDrawableEnd = 0x7f020010;
        public static final int ptrDrawableStart = 0x7f020011;
        public static final int ptrDrawableTop = 0x7f020012;
        public static final int ptrHeaderBackground = 0x7f020013;
        public static final int ptrHeaderSubTextColor = 0x7f020014;
        public static final int ptrHeaderTextAppearance = 0x7f020015;
        public static final int ptrHeaderTextColor = 0x7f020016;
        public static final int ptrListViewExtrasEnabled = 0x7f020017;
        public static final int ptrMode = 0x7f020018;
        public static final int ptrOverScroll = 0x7f020019;
        public static final int ptrRefreshableViewBackground = 0x7f02001a;
        public static final int ptrRotateDrawableWhilePulling = 0x7f02001b;
        public static final int ptrScrollingWhileRefreshingEnabled = 0x7f02001c;
        public static final int ptrShowIndicator = 0x7f02001d;
        public static final int ptrSubHeaderTextAppearance = 0x7f02001e;
        public static final int reverseLayout = 0x7f02001f;
        public static final int rightViewId = 0x7f020020;
        public static final int ruler_mode = 0x7f020021;
        public static final int ruler_style = 0x7f020022;
        public static final int spanCount = 0x7f020023;
        public static final int stackFromEnd = 0x7f020024;
        public static final int unit_bmp_height = 0x7f020025;
        public static final int unit_color = 0x7f020026;
        public static final int unit_visible = 0x7f020027;
    }
    public static final class dimen {
        public static final int fastscroll_default_thickness = 0x7f030000;
        public static final int fastscroll_margin = 0x7f030001;
        public static final int fastscroll_minimum_range = 0x7f030002;
        public static final int header_footer_left_right_padding = 0x7f030003;
        public static final int header_footer_top_bottom_padding = 0x7f030004;
        public static final int indicator_corner_radius = 0x7f030005;
        public static final int indicator_internal_padding = 0x7f030006;
        public static final int indicator_right_padding = 0x7f030007;
        public static final int item_touch_helper_max_drag_scroll_per_frame = 0x7f030008;
        public static final int item_touch_helper_swipe_escape_max_velocity = 0x7f030009;
        public static final int item_touch_helper_swipe_escape_velocity = 0x7f03000a;
    }
    public static final class drawable {
        public static final int default_ptr_flip = 0x7f040000;
        public static final int default_ptr_rotate = 0x7f040001;
        public static final int indicator_arrow = 0x7f040002;
        public static final int indicator_bg_bottom = 0x7f040003;
        public static final int indicator_bg_top = 0x7f040004;
    }
    public static final class id {
        public static final int fl_inner = 0x7f050002;
        public static final int gridview = 0x7f050004;
        public static final int item_touch_helper_previous_elevation = 0x7f050005;
        public static final int max = 0x7f050007;
        public static final int mid = 0x7f050008;
        public static final int min = 0x7f050009;
        public static final int pull_to_refresh_image = 0x7f05000e;
        public static final int pull_to_refresh_progress = 0x7f05000f;
        public static final int pull_to_refresh_sub_text = 0x7f050010;
        public static final int pull_to_refresh_text = 0x7f050011;
        public static final int ruler = 0x7f050013;
        public static final int scrollview = 0x7f050014;
        public static final int swipe_content = 0x7f050015;
        public static final int swipe_right = 0x7f050016;
        public static final int timeline = 0x7f050017;
        public static final int webview = 0x7f050018;
    }
    public static final class layout {
        public static final int pull_to_refresh_header_horizontal = 0x7f060000;
        public static final int pull_to_refresh_header_vertical = 0x7f060001;
        public static final int yanzhenjie_item_default = 0x7f060002;
    }
    public static final class string {
        public static final int pull_to_refresh_from_bottom_pull_label = 0x7f070000;
        public static final int pull_to_refresh_from_bottom_refreshing_label = 0x7f070001;
        public static final int pull_to_refresh_from_bottom_release_label = 0x7f070002;
        public static final int pull_to_refresh_pull_label = 0x7f070003;
        public static final int pull_to_refresh_refreshing_label = 0x7f070004;
        public static final int pull_to_refresh_release_label = 0x7f070005;
    }
    public static final class styleable {
        public static final int[] PullToRefresh = { 0x7f02000c, 0x7f02000d, 0x7f02000e, 0x7f02000f, 0x7f020010, 0x7f020011, 0x7f020012, 0x7f020013, 0x7f020014, 0x7f020015, 0x7f020016, 0x7f020017, 0x7f020018, 0x7f020019, 0x7f02001a, 0x7f02001b, 0x7f02001c, 0x7f02001d, 0x7f02001e };
        public static final int PullToRefresh_ptrAdapterViewBackground = 0;
        public static final int PullToRefresh_ptrAnimationStyle = 1;
        public static final int PullToRefresh_ptrDrawable = 2;
        public static final int PullToRefresh_ptrDrawableBottom = 3;
        public static final int PullToRefresh_ptrDrawableEnd = 4;
        public static final int PullToRefresh_ptrDrawableStart = 5;
        public static final int PullToRefresh_ptrDrawableTop = 6;
        public static final int PullToRefresh_ptrHeaderBackground = 7;
        public static final int PullToRefresh_ptrHeaderSubTextColor = 8;
        public static final int PullToRefresh_ptrHeaderTextAppearance = 9;
        public static final int PullToRefresh_ptrHeaderTextColor = 10;
        public static final int PullToRefresh_ptrListViewExtrasEnabled = 11;
        public static final int PullToRefresh_ptrMode = 12;
        public static final int PullToRefresh_ptrOverScroll = 13;
        public static final int PullToRefresh_ptrRefreshableViewBackground = 14;
        public static final int PullToRefresh_ptrRotateDrawableWhilePulling = 15;
        public static final int PullToRefresh_ptrScrollingWhileRefreshingEnabled = 16;
        public static final int PullToRefresh_ptrShowIndicator = 17;
        public static final int PullToRefresh_ptrSubHeaderTextAppearance = 18;
        public static final int[] RecyclerView = { 0x010100c4, 0x010100f1, 0x7f020001, 0x7f020002, 0x7f020003, 0x7f020004, 0x7f020005, 0x7f020006, 0x7f02001f, 0x7f020023, 0x7f020024 };
        public static final int RecyclerView_android_orientation = 0;
        public static final int RecyclerView_android_descendantFocusability = 1;
        public static final int RecyclerView_fastScrollEnabled = 2;
        public static final int RecyclerView_fastScrollHorizontalThumbDrawable = 3;
        public static final int RecyclerView_fastScrollHorizontalTrackDrawable = 4;
        public static final int RecyclerView_fastScrollVerticalThumbDrawable = 5;
        public static final int RecyclerView_fastScrollVerticalTrackDrawable = 6;
        public static final int RecyclerView_layoutManager = 7;
        public static final int RecyclerView_reverseLayout = 8;
        public static final int RecyclerView_spanCount = 9;
        public static final int RecyclerView_stackFromEnd = 10;
        public static final int[] Ruler = { 0x7f020007, 0x7f020008, 0x7f020009, 0x7f02000a, 0x7f02000b, 0x7f020021, 0x7f020025, 0x7f020026, 0x7f020027 };
        public static final int Ruler_mark_color = 0;
        public static final int Ruler_max_unit_count = 1;
        public static final int Ruler_min_unit = 2;
        public static final int Ruler_min_unit_size = 3;
        public static final int Ruler_per_unit_count = 4;
        public static final int Ruler_ruler_mode = 5;
        public static final int Ruler_unit_bmp_height = 6;
        public static final int Ruler_unit_color = 7;
        public static final int Ruler_unit_visible = 8;
        public static final int[] SwipeMenuLayout = { 0x7f020000, 0x7f020020 };
        public static final int SwipeMenuLayout_contentViewId = 0;
        public static final int SwipeMenuLayout_rightViewId = 1;
    }
}
