/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.fala.pulltorefresh.library.test;

public final class R {
  public static final class anim {
    public static final int slide_in_from_bottom=0x7f010000;
    public static final int slide_in_from_top=0x7f010001;
    public static final int slide_out_to_bottom=0x7f010002;
    public static final int slide_out_to_top=0x7f010003;
  }
  public static final class attr {
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int contentViewId=0x7f020000;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int fastScrollEnabled=0x7f020001;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int fastScrollHorizontalThumbDrawable=0x7f020002;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int fastScrollHorizontalTrackDrawable=0x7f020003;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int fastScrollVerticalThumbDrawable=0x7f020004;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int fastScrollVerticalTrackDrawable=0x7f020005;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int layoutManager=0x7f020006;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int mark_color=0x7f020007;
    /**
     * <p>May be an integer value, such as "<code>100</code>".
     */
    public static final int max_unit_count=0x7f020008;
    /**
     * <p>May be a floating point value, such as "<code>1.2</code>".
     */
    public static final int min_unit=0x7f020009;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int min_unit_size=0x7f02000a;
    /**
     * <p>May be an integer value, such as "<code>100</code>".
     */
    public static final int per_unit_count=0x7f02000b;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int ptrAdapterViewBackground=0x7f02000c;
    /**
     * <p>Must be one or more (separated by '|') of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>flip</td><td>1</td><td></td></tr>
     * <tr><td>rotate</td><td>0</td><td></td></tr>
     * </table>
     */
    public static final int ptrAnimationStyle=0x7f02000d;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int ptrDrawable=0x7f02000e;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int ptrDrawableBottom=0x7f02000f;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int ptrDrawableEnd=0x7f020010;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int ptrDrawableStart=0x7f020011;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int ptrDrawableTop=0x7f020012;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int ptrHeaderBackground=0x7f020013;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int ptrHeaderSubTextColor=0x7f020014;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int ptrHeaderTextAppearance=0x7f020015;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int ptrHeaderTextColor=0x7f020016;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int ptrListViewExtrasEnabled=0x7f020017;
    /**
     * <p>Must be one or more (separated by '|') of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>both</td><td>3</td><td></td></tr>
     * <tr><td>disabled</td><td>0</td><td></td></tr>
     * <tr><td>manualOnly</td><td>4</td><td></td></tr>
     * <tr><td>pullDownFromTop</td><td>1</td><td></td></tr>
     * <tr><td>pullFromEnd</td><td>2</td><td></td></tr>
     * <tr><td>pullFromStart</td><td>1</td><td></td></tr>
     * <tr><td>pullUpFromBottom</td><td>2</td><td></td></tr>
     * </table>
     */
    public static final int ptrMode=0x7f020018;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int ptrOverScroll=0x7f020019;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int ptrRefreshableViewBackground=0x7f02001a;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int ptrRotateDrawableWhilePulling=0x7f02001b;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int ptrScrollingWhileRefreshingEnabled=0x7f02001c;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int ptrShowIndicator=0x7f02001d;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int ptrSubHeaderTextAppearance=0x7f02001e;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int reverseLayout=0x7f02001f;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int rightViewId=0x7f020020;
    /**
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>ruler</td><td>0</td><td></td></tr>
     * <tr><td>timeline</td><td>1</td><td></td></tr>
     * </table>
     */
    public static final int ruler_mode=0x7f020021;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int ruler_style=0x7f020022;
    /**
     * <p>May be an integer value, such as "<code>100</code>".
     */
    public static final int spanCount=0x7f020023;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int stackFromEnd=0x7f020024;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int unit_bmp_height=0x7f020025;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int unit_color=0x7f020026;
    /**
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>max</td><td>1</td><td></td></tr>
     * <tr><td>mid</td><td>2</td><td></td></tr>
     * <tr><td>min</td><td>4</td><td></td></tr>
     * </table>
     */
    public static final int unit_visible=0x7f020027;
  }
  public static final class dimen {
    public static final int fastscroll_default_thickness=0x7f030000;
    public static final int fastscroll_margin=0x7f030001;
    public static final int fastscroll_minimum_range=0x7f030002;
    public static final int header_footer_left_right_padding=0x7f030003;
    public static final int header_footer_top_bottom_padding=0x7f030004;
    public static final int indicator_corner_radius=0x7f030005;
    public static final int indicator_internal_padding=0x7f030006;
    public static final int indicator_right_padding=0x7f030007;
    public static final int item_touch_helper_max_drag_scroll_per_frame=0x7f030008;
    public static final int item_touch_helper_swipe_escape_max_velocity=0x7f030009;
    public static final int item_touch_helper_swipe_escape_velocity=0x7f03000a;
  }
  public static final class drawable {
    public static final int default_ptr_flip=0x7f040000;
    public static final int default_ptr_rotate=0x7f040001;
    public static final int indicator_arrow=0x7f040002;
    public static final int indicator_bg_bottom=0x7f040003;
    public static final int indicator_bg_top=0x7f040004;
  }
  public static final class id {
    public static final int both=0x7f050000;
    public static final int disabled=0x7f050001;
    public static final int fl_inner=0x7f050002;
    public static final int flip=0x7f050003;
    public static final int gridview=0x7f050004;
    public static final int item_touch_helper_previous_elevation=0x7f050005;
    public static final int manualOnly=0x7f050006;
    public static final int max=0x7f050007;
    public static final int mid=0x7f050008;
    public static final int min=0x7f050009;
    public static final int pullDownFromTop=0x7f05000a;
    public static final int pullFromEnd=0x7f05000b;
    public static final int pullFromStart=0x7f05000c;
    public static final int pullUpFromBottom=0x7f05000d;
    public static final int pull_to_refresh_image=0x7f05000e;
    public static final int pull_to_refresh_progress=0x7f05000f;
    public static final int pull_to_refresh_sub_text=0x7f050010;
    public static final int pull_to_refresh_text=0x7f050011;
    public static final int rotate=0x7f050012;
    public static final int ruler=0x7f050013;
    public static final int scrollview=0x7f050014;
    public static final int swipe_content=0x7f050015;
    public static final int swipe_right=0x7f050016;
    public static final int timeline=0x7f050017;
    public static final int webview=0x7f050018;
  }
  public static final class layout {
    public static final int pull_to_refresh_header_horizontal=0x7f060000;
    public static final int pull_to_refresh_header_vertical=0x7f060001;
    public static final int yanzhenjie_item_default=0x7f060002;
  }
  public static final class string {
    public static final int pull_to_refresh_from_bottom_pull_label=0x7f070000;
    public static final int pull_to_refresh_from_bottom_refreshing_label=0x7f070001;
    public static final int pull_to_refresh_from_bottom_release_label=0x7f070002;
    public static final int pull_to_refresh_pull_label=0x7f070003;
    public static final int pull_to_refresh_refreshing_label=0x7f070004;
    public static final int pull_to_refresh_release_label=0x7f070005;
  }
  public static final class styleable {
    /**
     * Attributes that can be used with a PullToRefresh.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrAdapterViewBackground com.fala.pulltorefresh.library.test:ptrAdapterViewBackground}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrAnimationStyle com.fala.pulltorefresh.library.test:ptrAnimationStyle}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrDrawable com.fala.pulltorefresh.library.test:ptrDrawable}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrDrawableBottom com.fala.pulltorefresh.library.test:ptrDrawableBottom}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrDrawableEnd com.fala.pulltorefresh.library.test:ptrDrawableEnd}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrDrawableStart com.fala.pulltorefresh.library.test:ptrDrawableStart}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrDrawableTop com.fala.pulltorefresh.library.test:ptrDrawableTop}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrHeaderBackground com.fala.pulltorefresh.library.test:ptrHeaderBackground}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrHeaderSubTextColor com.fala.pulltorefresh.library.test:ptrHeaderSubTextColor}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrHeaderTextAppearance com.fala.pulltorefresh.library.test:ptrHeaderTextAppearance}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrHeaderTextColor com.fala.pulltorefresh.library.test:ptrHeaderTextColor}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrListViewExtrasEnabled com.fala.pulltorefresh.library.test:ptrListViewExtrasEnabled}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrMode com.fala.pulltorefresh.library.test:ptrMode}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrOverScroll com.fala.pulltorefresh.library.test:ptrOverScroll}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrRefreshableViewBackground com.fala.pulltorefresh.library.test:ptrRefreshableViewBackground}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrRotateDrawableWhilePulling com.fala.pulltorefresh.library.test:ptrRotateDrawableWhilePulling}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrScrollingWhileRefreshingEnabled com.fala.pulltorefresh.library.test:ptrScrollingWhileRefreshingEnabled}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrShowIndicator com.fala.pulltorefresh.library.test:ptrShowIndicator}</code></td><td></td></tr>
     * <tr><td><code>{@link #PullToRefresh_ptrSubHeaderTextAppearance com.fala.pulltorefresh.library.test:ptrSubHeaderTextAppearance}</code></td><td></td></tr>
     * </table>
     * @see #PullToRefresh_ptrAdapterViewBackground
     * @see #PullToRefresh_ptrAnimationStyle
     * @see #PullToRefresh_ptrDrawable
     * @see #PullToRefresh_ptrDrawableBottom
     * @see #PullToRefresh_ptrDrawableEnd
     * @see #PullToRefresh_ptrDrawableStart
     * @see #PullToRefresh_ptrDrawableTop
     * @see #PullToRefresh_ptrHeaderBackground
     * @see #PullToRefresh_ptrHeaderSubTextColor
     * @see #PullToRefresh_ptrHeaderTextAppearance
     * @see #PullToRefresh_ptrHeaderTextColor
     * @see #PullToRefresh_ptrListViewExtrasEnabled
     * @see #PullToRefresh_ptrMode
     * @see #PullToRefresh_ptrOverScroll
     * @see #PullToRefresh_ptrRefreshableViewBackground
     * @see #PullToRefresh_ptrRotateDrawableWhilePulling
     * @see #PullToRefresh_ptrScrollingWhileRefreshingEnabled
     * @see #PullToRefresh_ptrShowIndicator
     * @see #PullToRefresh_ptrSubHeaderTextAppearance
     */
    public static final int[] PullToRefresh={
        0x7f02000c, 0x7f02000d, 0x7f02000e, 0x7f02000f, 
        0x7f020010, 0x7f020011, 0x7f020012, 0x7f020013, 
        0x7f020014, 0x7f020015, 0x7f020016, 0x7f020017, 
        0x7f020018, 0x7f020019, 0x7f02001a, 0x7f02001b, 
        0x7f02001c, 0x7f02001d, 0x7f02001e
      };
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrAdapterViewBackground}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrAdapterViewBackground
     */
    public static final int PullToRefresh_ptrAdapterViewBackground=0;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrAnimationStyle}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>Must be one or more (separated by '|') of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>flip</td><td>1</td><td></td></tr>
     * <tr><td>rotate</td><td>0</td><td></td></tr>
     * </table>
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrAnimationStyle
     */
    public static final int PullToRefresh_ptrAnimationStyle=1;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrDrawable}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrDrawable
     */
    public static final int PullToRefresh_ptrDrawable=2;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrDrawableBottom}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrDrawableBottom
     */
    public static final int PullToRefresh_ptrDrawableBottom=3;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrDrawableEnd}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrDrawableEnd
     */
    public static final int PullToRefresh_ptrDrawableEnd=4;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrDrawableStart}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrDrawableStart
     */
    public static final int PullToRefresh_ptrDrawableStart=5;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrDrawableTop}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrDrawableTop
     */
    public static final int PullToRefresh_ptrDrawableTop=6;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrHeaderBackground}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrHeaderBackground
     */
    public static final int PullToRefresh_ptrHeaderBackground=7;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrHeaderSubTextColor}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrHeaderSubTextColor
     */
    public static final int PullToRefresh_ptrHeaderSubTextColor=8;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrHeaderTextAppearance}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrHeaderTextAppearance
     */
    public static final int PullToRefresh_ptrHeaderTextAppearance=9;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrHeaderTextColor}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrHeaderTextColor
     */
    public static final int PullToRefresh_ptrHeaderTextColor=10;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrListViewExtrasEnabled}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrListViewExtrasEnabled
     */
    public static final int PullToRefresh_ptrListViewExtrasEnabled=11;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrMode}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>Must be one or more (separated by '|') of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>both</td><td>3</td><td></td></tr>
     * <tr><td>disabled</td><td>0</td><td></td></tr>
     * <tr><td>manualOnly</td><td>4</td><td></td></tr>
     * <tr><td>pullDownFromTop</td><td>1</td><td></td></tr>
     * <tr><td>pullFromEnd</td><td>2</td><td></td></tr>
     * <tr><td>pullFromStart</td><td>1</td><td></td></tr>
     * <tr><td>pullUpFromBottom</td><td>2</td><td></td></tr>
     * </table>
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrMode
     */
    public static final int PullToRefresh_ptrMode=12;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrOverScroll}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrOverScroll
     */
    public static final int PullToRefresh_ptrOverScroll=13;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrRefreshableViewBackground}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrRefreshableViewBackground
     */
    public static final int PullToRefresh_ptrRefreshableViewBackground=14;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrRotateDrawableWhilePulling}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrRotateDrawableWhilePulling
     */
    public static final int PullToRefresh_ptrRotateDrawableWhilePulling=15;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrScrollingWhileRefreshingEnabled}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrScrollingWhileRefreshingEnabled
     */
    public static final int PullToRefresh_ptrScrollingWhileRefreshingEnabled=16;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrShowIndicator}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrShowIndicator
     */
    public static final int PullToRefresh_ptrShowIndicator=17;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ptrSubHeaderTextAppearance}
     * attribute's value can be found in the {@link #PullToRefresh} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:ptrSubHeaderTextAppearance
     */
    public static final int PullToRefresh_ptrSubHeaderTextAppearance=18;
    /**
     * Attributes that can be used with a RecyclerView.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #RecyclerView_android_orientation android:orientation}</code></td><td></td></tr>
     * <tr><td><code>{@link #RecyclerView_android_descendantFocusability android:descendantFocusability}</code></td><td></td></tr>
     * <tr><td><code>{@link #RecyclerView_fastScrollEnabled com.fala.pulltorefresh.library.test:fastScrollEnabled}</code></td><td></td></tr>
     * <tr><td><code>{@link #RecyclerView_fastScrollHorizontalThumbDrawable com.fala.pulltorefresh.library.test:fastScrollHorizontalThumbDrawable}</code></td><td></td></tr>
     * <tr><td><code>{@link #RecyclerView_fastScrollHorizontalTrackDrawable com.fala.pulltorefresh.library.test:fastScrollHorizontalTrackDrawable}</code></td><td></td></tr>
     * <tr><td><code>{@link #RecyclerView_fastScrollVerticalThumbDrawable com.fala.pulltorefresh.library.test:fastScrollVerticalThumbDrawable}</code></td><td></td></tr>
     * <tr><td><code>{@link #RecyclerView_fastScrollVerticalTrackDrawable com.fala.pulltorefresh.library.test:fastScrollVerticalTrackDrawable}</code></td><td></td></tr>
     * <tr><td><code>{@link #RecyclerView_layoutManager com.fala.pulltorefresh.library.test:layoutManager}</code></td><td></td></tr>
     * <tr><td><code>{@link #RecyclerView_reverseLayout com.fala.pulltorefresh.library.test:reverseLayout}</code></td><td></td></tr>
     * <tr><td><code>{@link #RecyclerView_spanCount com.fala.pulltorefresh.library.test:spanCount}</code></td><td></td></tr>
     * <tr><td><code>{@link #RecyclerView_stackFromEnd com.fala.pulltorefresh.library.test:stackFromEnd}</code></td><td></td></tr>
     * </table>
     * @see #RecyclerView_android_orientation
     * @see #RecyclerView_android_descendantFocusability
     * @see #RecyclerView_fastScrollEnabled
     * @see #RecyclerView_fastScrollHorizontalThumbDrawable
     * @see #RecyclerView_fastScrollHorizontalTrackDrawable
     * @see #RecyclerView_fastScrollVerticalThumbDrawable
     * @see #RecyclerView_fastScrollVerticalTrackDrawable
     * @see #RecyclerView_layoutManager
     * @see #RecyclerView_reverseLayout
     * @see #RecyclerView_spanCount
     * @see #RecyclerView_stackFromEnd
     */
    public static final int[] RecyclerView={
        0x010100c4, 0x010100f1, 0x7f020001, 0x7f020002, 
        0x7f020003, 0x7f020004, 0x7f020005, 0x7f020006, 
        0x7f02001f, 0x7f020023, 0x7f020024
      };
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#descendantFocusability}
     * attribute's value can be found in the {@link #RecyclerView} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>afterDescendants</td><td>1</td><td></td></tr>
     * <tr><td>beforeDescendants</td><td>0</td><td></td></tr>
     * <tr><td>blocksDescendants</td><td>2</td><td></td></tr>
     * </table>
     *
     * @attr name android:descendantFocusability
     */
    public static final int RecyclerView_android_descendantFocusability=1;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#orientation}
     * attribute's value can be found in the {@link #RecyclerView} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>horizontal</td><td>0</td><td></td></tr>
     * <tr><td>vertical</td><td>1</td><td></td></tr>
     * </table>
     *
     * @attr name android:orientation
     */
    public static final int RecyclerView_android_orientation=0;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#fastScrollEnabled}
     * attribute's value can be found in the {@link #RecyclerView} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:fastScrollEnabled
     */
    public static final int RecyclerView_fastScrollEnabled=2;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#fastScrollHorizontalThumbDrawable}
     * attribute's value can be found in the {@link #RecyclerView} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:fastScrollHorizontalThumbDrawable
     */
    public static final int RecyclerView_fastScrollHorizontalThumbDrawable=3;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#fastScrollHorizontalTrackDrawable}
     * attribute's value can be found in the {@link #RecyclerView} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:fastScrollHorizontalTrackDrawable
     */
    public static final int RecyclerView_fastScrollHorizontalTrackDrawable=4;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#fastScrollVerticalThumbDrawable}
     * attribute's value can be found in the {@link #RecyclerView} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:fastScrollVerticalThumbDrawable
     */
    public static final int RecyclerView_fastScrollVerticalThumbDrawable=5;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#fastScrollVerticalTrackDrawable}
     * attribute's value can be found in the {@link #RecyclerView} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:fastScrollVerticalTrackDrawable
     */
    public static final int RecyclerView_fastScrollVerticalTrackDrawable=6;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#layoutManager}
     * attribute's value can be found in the {@link #RecyclerView} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.fala.pulltorefresh.library.test:layoutManager
     */
    public static final int RecyclerView_layoutManager=7;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#reverseLayout}
     * attribute's value can be found in the {@link #RecyclerView} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:reverseLayout
     */
    public static final int RecyclerView_reverseLayout=8;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#spanCount}
     * attribute's value can be found in the {@link #RecyclerView} array.
     *
     * <p>May be an integer value, such as "<code>100</code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:spanCount
     */
    public static final int RecyclerView_spanCount=9;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#stackFromEnd}
     * attribute's value can be found in the {@link #RecyclerView} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:stackFromEnd
     */
    public static final int RecyclerView_stackFromEnd=10;
    /**
     * Attributes that can be used with a Ruler.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #Ruler_mark_color com.fala.pulltorefresh.library.test:mark_color}</code></td><td></td></tr>
     * <tr><td><code>{@link #Ruler_max_unit_count com.fala.pulltorefresh.library.test:max_unit_count}</code></td><td></td></tr>
     * <tr><td><code>{@link #Ruler_min_unit com.fala.pulltorefresh.library.test:min_unit}</code></td><td></td></tr>
     * <tr><td><code>{@link #Ruler_min_unit_size com.fala.pulltorefresh.library.test:min_unit_size}</code></td><td></td></tr>
     * <tr><td><code>{@link #Ruler_per_unit_count com.fala.pulltorefresh.library.test:per_unit_count}</code></td><td></td></tr>
     * <tr><td><code>{@link #Ruler_ruler_mode com.fala.pulltorefresh.library.test:ruler_mode}</code></td><td></td></tr>
     * <tr><td><code>{@link #Ruler_unit_bmp_height com.fala.pulltorefresh.library.test:unit_bmp_height}</code></td><td></td></tr>
     * <tr><td><code>{@link #Ruler_unit_color com.fala.pulltorefresh.library.test:unit_color}</code></td><td></td></tr>
     * <tr><td><code>{@link #Ruler_unit_visible com.fala.pulltorefresh.library.test:unit_visible}</code></td><td></td></tr>
     * </table>
     * @see #Ruler_mark_color
     * @see #Ruler_max_unit_count
     * @see #Ruler_min_unit
     * @see #Ruler_min_unit_size
     * @see #Ruler_per_unit_count
     * @see #Ruler_ruler_mode
     * @see #Ruler_unit_bmp_height
     * @see #Ruler_unit_color
     * @see #Ruler_unit_visible
     */
    public static final int[] Ruler={
        0x7f020007, 0x7f020008, 0x7f020009, 0x7f02000a, 
        0x7f02000b, 0x7f020021, 0x7f020025, 0x7f020026, 
        0x7f020027
      };
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#mark_color}
     * attribute's value can be found in the {@link #Ruler} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:mark_color
     */
    public static final int Ruler_mark_color=0;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#max_unit_count}
     * attribute's value can be found in the {@link #Ruler} array.
     *
     * <p>May be an integer value, such as "<code>100</code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:max_unit_count
     */
    public static final int Ruler_max_unit_count=1;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#min_unit}
     * attribute's value can be found in the {@link #Ruler} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:min_unit
     */
    public static final int Ruler_min_unit=2;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#min_unit_size}
     * attribute's value can be found in the {@link #Ruler} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.fala.pulltorefresh.library.test:min_unit_size
     */
    public static final int Ruler_min_unit_size=3;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#per_unit_count}
     * attribute's value can be found in the {@link #Ruler} array.
     *
     * <p>May be an integer value, such as "<code>100</code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:per_unit_count
     */
    public static final int Ruler_per_unit_count=4;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#ruler_mode}
     * attribute's value can be found in the {@link #Ruler} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>ruler</td><td>0</td><td></td></tr>
     * <tr><td>timeline</td><td>1</td><td></td></tr>
     * </table>
     *
     * @attr name com.fala.pulltorefresh.library.test:ruler_mode
     */
    public static final int Ruler_ruler_mode=5;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#unit_bmp_height}
     * attribute's value can be found in the {@link #Ruler} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.fala.pulltorefresh.library.test:unit_bmp_height
     */
    public static final int Ruler_unit_bmp_height=6;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#unit_color}
     * attribute's value can be found in the {@link #Ruler} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:unit_color
     */
    public static final int Ruler_unit_color=7;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#unit_visible}
     * attribute's value can be found in the {@link #Ruler} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>max</td><td>1</td><td></td></tr>
     * <tr><td>mid</td><td>2</td><td></td></tr>
     * <tr><td>min</td><td>4</td><td></td></tr>
     * </table>
     *
     * @attr name com.fala.pulltorefresh.library.test:unit_visible
     */
    public static final int Ruler_unit_visible=8;
    /**
     * Attributes that can be used with a SwipeMenuLayout.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #SwipeMenuLayout_contentViewId com.fala.pulltorefresh.library.test:contentViewId}</code></td><td></td></tr>
     * <tr><td><code>{@link #SwipeMenuLayout_rightViewId com.fala.pulltorefresh.library.test:rightViewId}</code></td><td></td></tr>
     * </table>
     * @see #SwipeMenuLayout_contentViewId
     * @see #SwipeMenuLayout_rightViewId
     */
    public static final int[] SwipeMenuLayout={
        0x7f020000, 0x7f020020
      };
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#contentViewId}
     * attribute's value can be found in the {@link #SwipeMenuLayout} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:contentViewId
     */
    public static final int SwipeMenuLayout_contentViewId=0;
    /**
     * <p>This symbol is the offset where the {@link com.fala.pulltorefresh.library.test.R.attr#rightViewId}
     * attribute's value can be found in the {@link #SwipeMenuLayout} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.fala.pulltorefresh.library.test:rightViewId
     */
    public static final int SwipeMenuLayout_rightViewId=1;
  }
}